#pragma once
#include <cstdint>

const int MAX_ENTITIES = 5000;

using Entity = unsigned int;

enum ComponentType : std::uint8_t {
  COMP_TRANSFORM = 0,
  COMP_SPRITE,
  COMP_VELOCITY,
  COMP_INPUT,
  COMP_UICANVAS,
  COMP_UI,
  COMP_SCRIPT,
  COMP_SPRITE_ANIMATION,
  COMP_RIGIDPHYSICS,
  COMP_CIRCLECOLLIDER,
  COMP_BOXCOLLIDER,
  COMP_NAME,
  COMP_MATERIAL,
  COMP_LIGHT,
  COMP_CAMERA,
  COMP_COUNT
};